import type { Metadata } from "next";
import "./globals.css"; // Pastikan file globals.css sudah sesuai dengan kebutuhan Anda

// Import font-face
const fontFaceStyle = `
  @font-face {
    font-family: 'AnotherDangerDemo';
    src: url('/fonts/AnotherDanger-Demo.otf') format('truetype');
  }
`;

export const metadata: Metadata = {
  title: "Cek Khodam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style dangerouslySetInnerHTML={{ __html: fontFaceStyle }} />
      </head>
      <body style={{ fontFamily: 'AnotherDangerDemo' }}>{children}</body>
    </html>
  );
}
